### PR TITLE
A hook to complete DNS challenge using OVH API.

### PR DESCRIPTION
**Pull request by asquelt**

### CODE REVIEW

**Comment by hlandau** [comment]
Nice.

Do you mind if I list you as the maintainer for this script?

**Comment by asquelt** [comment]
sure, i don't mind. this is simple script that i can maintain.

it requires small change in upstream (ovh-cli), so let's hold it for a while until it's fixed.

**Comment by asquelt** [comment]
upstream is fixed, we can release it.

**Comment by hlandau** [comment]
Thanks.

**Pull request merged**
