### PR TITLE
ignore dot files in permission checker

### PR DESCRIPTION
**Pull request by gregorg**
An answer to issue #153

Permission checker will ignore `.*` in /var/lib/acme directory

### CODE REVIEW

**Comment by gregorg** [comment]
Note that the builds fails because of Boulder, not the PR.

**Comment by cpu** [comment]
@gregorg - I took a crack at fixing the build failure in https://github.com/hlandau/acme/pull/238 The issue isn't Boulder itself but the patch applied on top of Boulder's config files by acmetool.

**Comment by gregorg** [comment]
Yeah ! I did it ! :dancer:

**Comment by hlandau** [comment]
Thanks. I ended up implementing this a little differently.

**Pull request closed without merging**
